version: '1'
services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: user_password
      MONGO_INITDB_DATABASE: peoplemanager
    ports:
      - "27017:27017"
    volumes:
      - ./containers/mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

